name: Run unit tests

on: push

jobs:
  build-and-run-unit-tests:
    name: Build and run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]
      - name: Test with pytest
        run: |
          pytest
